%code requires{
  #include "abstsyntree.hpp"

  #include <cassert>
	#include <fstream>
	#include <string>
  extern nodePtr g_root; // A way of getting the AST out

  //! This is to fix problems when generating C++
  // We are declaring the functions provided by Flex, so
  // that Bison generated code can call them.
  int yylex(void);
  void yyerror(const char *);
}


//The %union DECL specifies the entire collection of possible data types for
//semantic values. The keyword %union is followed by braced code containing the same
//thing that goes inside a union in C.

%union{
  nodePtr expr;
  double number;
  std::string *string;
}

%token T_NUMBER T_IDENTIFIER T_STRING T_CONST
%token T_PLUS T_MINUS T_DIVIDE T_STAR T_MOD
%token T_POINT T_INCR T_DECR T_LSHIFT T_RSHIFT T_EQ T_NEQ T_GT T_GTE T_LT T_LTE T_NOT
%token T_AND T_OR T_BWXOR T_BWAND T_BWOR T_BWNOT
%token  T_EQMULT T_EQDIV T_EQMOD T_EQPLUS T_EQMINUS T_EQLSHIFT T_EQRSHIFT T_ASSIGN T_EQEXPONENT T_EQBWOR T_EQBWAND
%token  T_TYPE_NAME T_SIZEOF T_SEMI T_QBEGIN T_QEND T_DOT T_COMM

%token T_TYPEDEF T_EXTERN T_STATIC T_AUTO T_REGISTER
%token T_CHAR T_SHORT T_INT T_LONG T_SIGNED T_UNSIGNED T_FLOAT T_DOUBLE T_VOLATILE T_VOID
%token T_STRUCT T_UNION T_ENUM T_ELL
%token T_LBRACKET T_RBRACKET T_LSQBRACKET T_RSQBRACKET T_LCBRACKET T_RCBRACKET

%token T_CASE T_DEFAULT T_IF T_ELSE T_SWITCH T_WHILE T_DO T_FOR T_GOTO T_CONTINUE T_BREAK T_RETURN



%type <expr> PRI_EXPR POSTFIX_EXPR ARG_EXPR_LIST UNARY_EXPR UNARY_OP
%type <expr> CAST_EXPR MULTIPLICATIVE_EXPR ADDITIVE_EXPR SHFT_EXPR REL_EXPR EQ_EXPR AND_EXPR

%type <expr> EXCL_OR_EXPR INCL_OR_EXPR LOGI_AND_EXPR LOGI_OR_EXPR COND_EXPR ASSIGN_EXPR ASSIGN_OP EXPR CONST_EXPR
%type <expr> DECL DECL_SPECS INIT_DECLARATOR_LIST INIT_DECLARATOR STRGE_CLASS_SPEC TYPE_SPEC STRUCT_OR_UNION_SPEC
%type <expr> STRUCT_OR_UNION STRUCT_DECL_LIST STRUCT_DECL SPEC_QUAL_LIST STRUCT_DECLARATOR_LIST STRUCT_DECLARATOR
%type <expr> ENUM_SPEC ENUM_LIST ENUM TYPE_QUAL DECLARATOR
%type <expr> DIREC_DECLARATOR POINTER TYPE_QUAL_LIST PARAM_TYPE_LIST PARAM_LIST PARAM_DECL ID_LIST TYPE_NAME
%type <expr> ABST_DECLARATOR DIR_ABST_DECLARATOR INIT INIT_LIST STMT LBL_STMT COMP_STMT DECL_LIST STMT_LIST EXPR_STMT
%type <expr> SELEC_STMT ITER_STMT JMP_STMT ROOT_NODE

%type <number> T_NUMBER
%type <string> T_IDENTIFIER T_STRING


%start ROOT_NODE

%%

PRI_EXPR//check
	: T_IDENTIFIER { $$ = new identifier(*$1);}
	| T_NUMBER { $$ = new constant($1);}
	| T_STRING { $$ = new str_lit(*$1);}
	| T_LBRACKET EXPR T_RBRACKET
	;

POSTFIX_EXPR
	: PRI_EXPR
	| POSTFIX_EXPR T_LSQBRACKET EXPR T_RSQBRACKET
	| POSTFIX_EXPR T_LBRACKET T_RBRACKET //FUNCTIONS//FUNCTIONS//FUNCTIONS
	| POSTFIX_EXPR T_LBRACKET ARG_EXPR_LIST T_RBRACKET
	| POSTFIX_EXPR T_DOT T_IDENTIFIER
	| POSTFIX_EXPR T_POINT T_IDENTIFIER
	| POSTFIX_EXPR T_INCR
	| POSTFIX_EXPR T_DECR
	;

ARG_EXPR_LIST
	: ASSIGN_EXPR
	| ARG_EXPR_LIST T_COMM ASSIGN_EXPR
	;

UNARY_EXPR
	: POSTFIX_EXPR
	| T_INCR UNARY_EXPR
	| T_DECR UNARY_EXPR
	| UNARY_OP CAST_EXPR
	| T_SIZEOF UNARY_EXPR
	| T_SIZEOF T_LBRACKET TYPE_NAME T_RBRACKET
	;

UNARY_OP
	: T_BWAND
	| T_STAR
	| T_PLUS
	| T_MINUS
	| T_BWNOT
	| T_NOT
	;

CAST_EXPR
	: UNARY_EXPR
	| T_LBRACKET TYPE_NAME T_RBRACKET CAST_EXPR
	;

MULTIPLICATIVE_EXPR
	: CAST_EXPR
	| MULTIPLICATIVE_EXPR T_STAR CAST_EXPR { $$ = new times_expr($1, $3);}
	| MULTIPLICATIVE_EXPR T_DIVIDE CAST_EXPR { $$ = new div_expr($1, $3);}
	| MULTIPLICATIVE_EXPR T_MOD CAST_EXPR { $$ = new mod_expr($1, $3);}
	;

ADDITIVE_EXPR
	: MULTIPLICATIVE_EXPR
	| ADDITIVE_EXPR T_PLUS MULTIPLICATIVE_EXPR { $$ = new times_expr($1, $3);}
	| ADDITIVE_EXPR T_MINUS MULTIPLICATIVE_EXPR { $$ = new minus_expr($1, $3);}
	;

SHFT_EXPR
	: ADDITIVE_EXPR
	| SHFT_EXPR T_LSHIFT ADDITIVE_EXPR
	| SHFT_EXPR T_RSHIFT ADDITIVE_EXPR
	;

REL_EXPR
	: SHFT_EXPR
	| REL_EXPR T_LT SHFT_EXPR
	| REL_EXPR T_GT SHFT_EXPR
	| REL_EXPR T_LTE SHFT_EXPR
	| REL_EXPR T_GTE SHFT_EXPR
	;

EQ_EXPR
	: REL_EXPR
	| EQ_EXPR T_EQ REL_EXPR
	| EQ_EXPR T_NEQ REL_EXPR
	;

AND_EXPR
	: EQ_EXPR
	| AND_EXPR T_BWAND EQ_EXPR
	;

EXCL_OR_EXPR
	: AND_EXPR
	| EXCL_OR_EXPR T_BWXOR AND_EXPR
	;

INCL_OR_EXPR
	: EXCL_OR_EXPR
	| INCL_OR_EXPR T_OR EXCL_OR_EXPR
	;

LOGI_AND_EXPR
	: INCL_OR_EXPR
	| LOGI_AND_EXPR T_AND INCL_OR_EXPR
	;

LOGI_OR_EXPR
	: LOGI_AND_EXPR
	| LOGI_OR_EXPR T_BWOR LOGI_AND_EXPR
	;

COND_EXPR
	: LOGI_OR_EXPR
	| LOGI_OR_EXPR T_QBEGIN EXPR T_QEND COND_EXPR
	;

ASSIGN_EXPR
	: COND_EXPR
	| UNARY_EXPR ASSIGN_OP ASSIGN_EXPR
	;

ASSIGN_OP
	: T_ASSIGN //check
	| T_EQMULT
	| T_EQDIV
	| T_EQMOD
	| T_EQPLUS
	| T_EQMINUS
	| T_EQLSHIFT
	| T_EQRSHIFT
	| T_EQBWAND
	| T_EQEXPONENT
	| T_EQBWOR
	;

EXPR
	: ASSIGN_EXPR
	| EXPR T_COMM ASSIGN_EXPR
	;

CONST_EXPR
	: COND_EXPR
	;

DECL
	: DECL_SPECS T_SEMI
	| DECL_SPECS INIT_DECLARATOR_LIST T_SEMI
	;

DECL_SPECS
	: STRGE_CLASS_SPEC
	| STRGE_CLASS_SPEC DECL_SPECS
	| TYPE_SPEC
	| TYPE_SPEC DECL_SPECS
	| TYPE_QUAL
	| TYPE_QUAL DECL_SPECS
	;

INIT_DECLARATOR_LIST
	: INIT_DECLARATOR
	| INIT_DECLARATOR_LIST T_COMM INIT_DECLARATOR
	;

INIT_DECLARATOR
	: DECLARATOR
	| DECLARATOR T_ASSIGN INIT
	;

STRGE_CLASS_SPEC
	: T_TYPEDEF //check?
	| T_EXTERN
	| T_STATIC
	| T_AUTO
	| T_REGISTER
	;

TYPE_SPEC
	: T_VOID
	| T_CHAR
	| T_SHORT
	| T_INT
	| T_LONG
	| T_FLOAT
	| T_DOUBLE
	| T_SIGNED
	| T_UNSIGNED
	| STRUCT_OR_UNION_SPEC
	| ENUM_SPEC
	| T_TYPE_NAME
	;

STRUCT_OR_UNION_SPEC
	: STRUCT_OR_UNION T_IDENTIFIER T_LCBRACKET STRUCT_DECL_LIST T_RCBRACKET
	| STRUCT_OR_UNION T_LCBRACKET STRUCT_DECL_LIST T_RCBRACKET
	| STRUCT_OR_UNION T_IDENTIFIER
	;

STRUCT_OR_UNION
	: T_STRUCT
	| T_UNION
	;

STRUCT_DECL_LIST
	: STRUCT_DECL
	| STRUCT_DECL_LIST STRUCT_DECL
	;

STRUCT_DECL
	: SPEC_QUAL_LIST STRUCT_DECLARATOR_LIST T_SEMI
	;

SPEC_QUAL_LIST
	: TYPE_SPEC SPEC_QUAL_LIST
	| TYPE_SPEC
	| TYPE_QUAL SPEC_QUAL_LIST
	| TYPE_QUAL
	;

STRUCT_DECLARATOR_LIST
	: STRUCT_DECLARATOR
	| STRUCT_DECLARATOR_LIST T_COMM STRUCT_DECLARATOR
	;

STRUCT_DECLARATOR
	: DECLARATOR
	| T_QEND CONST_EXPR
	| DECLARATOR T_QEND CONST_EXPR
	;

ENUM_SPEC
	: T_ENUM T_LCBRACKET ENUM_LIST T_RCBRACKET
	| T_ENUM T_IDENTIFIER T_LCBRACKET ENUM_LIST T_RCBRACKET
	| T_ENUM T_IDENTIFIER
	;

ENUM_LIST
	: ENUM
	| ENUM_LIST T_COMM ENUM
	;

ENUM
	: T_IDENTIFIER
	| T_IDENTIFIER T_ASSIGN CONST_EXPR
	;

TYPE_QUAL
	: T_CONST
	| T_VOLATILE
	;

DECLARATOR
	: POINTER DIREC_DECLARATOR
	| DIREC_DECLARATOR
	;

DIREC_DECLARATOR
	: T_IDENTIFIER
	| T_LBRACKET DECLARATOR T_RBRACKET
	| DIREC_DECLARATOR T_LSQBRACKET CONST_EXPR T_RSQBRACKET
	| DIREC_DECLARATOR T_LSQBRACKET T_RSQBRACKET
	| DIREC_DECLARATOR T_LBRACKET PARAM_TYPE_LIST T_RBRACKET
	| DIREC_DECLARATOR T_LBRACKET ID_LIST T_RBRACKET
	| DIREC_DECLARATOR T_LBRACKET T_RBRACKET
	;

POINTER
	: T_STAR
	| T_STAR TYPE_QUAL_LIST
	| T_STAR POINTER
	| T_STAR TYPE_QUAL_LIST POINTER
	;

TYPE_QUAL_LIST
	: TYPE_QUAL
	| TYPE_QUAL_LIST TYPE_QUAL
	;


PARAM_TYPE_LIST
	: PARAM_LIST
	| PARAM_LIST T_COMM T_ELL
	;

PARAM_LIST
	: PARAM_DECL
	| PARAM_LIST T_COMM PARAM_DECL
	;

PARAM_DECL
	: DECL_SPECS DECLARATOR
	| DECL_SPECS ABST_DECLARATOR
	| DECL_SPECS
	;

ID_LIST
	: T_IDENTIFIER
	| ID_LIST T_COMM T_IDENTIFIER
	;

TYPE_NAME
	: SPEC_QUAL_LIST
	| SPEC_QUAL_LIST ABST_DECLARATOR
	;

ABST_DECLARATOR
	: POINTER
	| DIR_ABST_DECLARATOR
	| POINTER DIR_ABST_DECLARATOR
	;

DIR_ABST_DECLARATOR
	: T_LBRACKET ABST_DECLARATOR T_RBRACKET
	| T_LSQBRACKET T_RSQBRACKET
	| T_LSQBRACKET CONST_EXPR T_RSQBRACKET
	| DIR_ABST_DECLARATOR T_LSQBRACKET T_RSQBRACKET
	| DIR_ABST_DECLARATOR T_LSQBRACKET CONST_EXPR T_RSQBRACKET
	| T_LBRACKET T_RBRACKET
	| T_LBRACKET PARAM_TYPE_LIST T_RBRACKET
	| DIR_ABST_DECLARATOR T_LBRACKET T_RBRACKET
	| DIR_ABST_DECLARATOR T_LBRACKET PARAM_TYPE_LIST T_RBRACKET
	;

INIT
	: ASSIGN_EXPR
	| T_LCBRACKET INIT_LIST T_RCBRACKET
	| T_LCBRACKET INIT_LIST T_COMM T_RCBRACKET
	;

INIT_LIST
	: INIT
	| INIT_LIST T_COMM INIT
	;

STMT
	: LBL_STMT
	| COMP_STMT
	| EXPR_STMT
	| SELEC_STMT
	| ITER_STMT
	| JMP_STMT
	;

LBL_STMT
	: T_IDENTIFIER T_QEND STMT
	| T_CASE CONST_EXPR T_QEND STMT
	| T_DEFAULT T_QEND STMT
	;

COMP_STMT
	: T_LCBRACKET T_RCBRACKET
	| T_LCBRACKET STMT_LIST T_RCBRACKET
	| T_LCBRACKET DECL_LIST T_RCBRACKET
	| T_LCBRACKET DECL_LIST STMT_LIST T_RCBRACKET
	;

DECL_LIST
	: DECL
	| DECL_LIST DECL
	;

STMT_LIST
	: STMT
	| STMT_LIST STMT
	;

EXPR_STMT
	: T_SEMI
	| EXPR T_SEMI
	;

SELEC_STMT
	: T_IF T_LBRACKET EXPR T_RBRACKET STMT { $$ = new ifelse_stmt($1,$3);}
	| T_IF T_LBRACKET EXPR T_RBRACKET STMT T_ELSE STMT { $$ = new ifelse_stmt($1, $3);}
	| T_SWITCH T_LBRACKET EXPR T_RBRACKET STMT
	;

ITER_STMT
	: T_WHILE T_LBRACKET EXPR T_RBRACKET STMT  { $$ = new while_stmt($1, $3);}
	| T_DO STMT T_WHILE T_LBRACKET EXPR T_RBRACKET T_SEMI
	| T_FOR T_LBRACKET EXPR_STMT EXPR_STMT T_RBRACKET STMT
	| T_FOR T_LBRACKET EXPR_STMT EXPR_STMT EXPR T_RBRACKET STMT
	;

JMP_STMT
	: T_GOTO T_IDENTIFIER T_SEMI
	| T_CONTINUE T_SEMI
	| T_BREAK T_SEMI
	| T_RETURN T_SEMI
	| T_RETURN EXPR T_SEMI
	;

ROOT_NODE
	: EXT_DECL
	| ROOT_NODE EXT_DECL
	;
EXT_DECL
	: FUNC_DEF
	| DECL
	;

FUNC_DEF
	: DECL_SPECS DECLARATOR DECL_LIST COMP_STMT
	| DECL_SPECS DECLARATOR COMP_STMT
	| DECLARATOR DECL_LIST COMP_STMT
	| DECLARATOR COMP_STMT
	;

	%%

	nodePtr g_root;
	extern FILE *yyin;
	const nodePtr parseAST(FILE* src){
	  g_root=0;
		yyin=src;
	  yyparse();
	  return g_root;
	}
